[package]
name = "ip_notifier"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
serenity = { version = "0.12.4", features = ["client", "gateway", "rustls_backend", "model"] }
tokio = { version = "1.44.2", features = ["full"] }
once_cell = "1.21.3"
chrono = "0.4.40"
anyhow = "1.0.98"
